version: "3.6"
services:
  service_nginx:
    image: nginx:alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ./src/backend/:/app
      - ./build/nginx/conf.d:/etc/nginx/conf.d
      - ./build/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ./build/nginx/fastcgi-php.conf:/etc/nginx/fastcgi-php.conf
      - vendor:/app/vendor
      - repository:/app/repository
    ports:
      - ${NGINX_PROXY_SERVICE_PORT}
    depends_on:
      - service_php_fpm

  service_php_fpm:
    build:
      context: ./
      dockerfile: ./build/php/Dockerfile
    working_dir: /app
    restart: always
    env_file:
      - ./src/backend/.env
    volumes:
      - ./src/backend/:/app
      - vendor:/app/vendor
      - repository:/app/repository
    depends_on:
      - service_db_mysql

  service_db_mysql:
    image: mysql:5.7.28
    restart: always
    env_file:
      - .env
    ports:
      - ${MYSQL_SERVICE_PORT}
    volumes:
      - mysql_data:/var/lib/mysql/
      - ./build/mysql/config:/etc/mysql/conf.d/

volumes:
  vendor:
  repository:
  mysql_data:
