<div id="wrapper">
    <h1>Maze RPG Tactics</h1>

    <div class="content">
        <div class="status-bar box-shadow">
            <?php foreach ($game->statuses as $status) {
                echo $status;
            } ?>
        </div>
        <div class="playboard box-shadow">
            <?php echo $game->playboard ?>
        </div>
        <div class="info-bar box-shadow">
            <div class="board-actions">
                <?php if (!empty($game->user['username'])) { ?>
                    <div class="refresh-button" title="Refreshes current room">Refresh</div>
                    <div class="reset-button" title="Resets to level 1 room 0">New game</div>
                <?php } ?>
            </div>
            <div class="top-players">
                <?php if (!empty($game->players)) { ?>
                    <h2>TOP PLAYERS</h2>
                    <div class="player">
                        <div class="player-username">
                            IGN
                        </div>
                        <div class="player-points">
                            POINTS
                        </div>
                        <div class="player-bosses">
                            LVL
                        </div>
                        <div class="player-bosses">
                            &#9825;
                        </div>
                    </div>
                    <?php foreach ($game->players as $player) { ?>
                        <div class="player">
                            <div class="player-username">
                                <div class="marquee"><span><?=$player['username']?></span></div>
                            </div>
                            <div class="player-points">
                                <?=$player['points']?>
                            </div>
                            <div class="player-bosses">
                                <?=$player['level']?>
                            </div>
                            <div class="player-bosses">
                                <?=$player['health_value'] > 0 ? 'Alive' : 'Dead'?>
                            </div>
                        </div>
                    <?php } ?>
                <?php } ?>
            </div>
        </div>
    </div>
    <div style="text-align:center">
        <p>Casual dungeon tactic runner based on Phalcon.</p>
        <p>Oh my, the meaningful words, scenes and game itself! The perfect mixture of a drama and spiritual ending! Not
            to mention the great plot and characters! Truly, a masterpiece.</p>
    </div>
</div>
