<div id="wrapper">
    <h1>Maze RPG Tactics</h1>
    
    <div class="content">
        <div class="status-bar box-shadow">
            <?
            foreach($data['status'] as $div)
            {
                echo $div;
            }
            ?>
        </div>
        <div class="playboard box-shadow">
            <?=$data['playboard']?>
        </div>
        <div class="info-bar box-shadow">
            <div class="board-actions">
                <? if(!empty($data['user']['username'])){?>
                    <div class="refresh-button" title="Refreshes current room">Refresh</div>
                    <div class="reset-button" title="Resets to level 1 room 0">New game</div>
                <?}?>
            </div>
            <div class="top-players">
                <? if(!empty($data['top'])){?>
                    <h2>TOP PLAYERS</h2>
                    <div class="player">
                        <div class="player-username">
                            IGN
                        </div>
                        <div class="player-points">
                            POINTS
                        </div>
                        <div class="player-bosses">
                            LVL
                        </div>
                        <div class="player-bosses">
                            &#9825;
                        </div>
                    </div>
                    <? foreach($data['top'] as $player){ ?>
                        <div class="player">
                            <div class="player-username">
                                <div class="marquee"><span><?=$player->username?></span></div>
                            </div>
                            <div class="player-points">
                                <?=$player->points?>
                            </div>
                            <div class="player-bosses">
                                <?=$player->level?>
                            </div>
                            <div class="player-bosses">
                                <?=$player->health_value > 0 ? 'Alive' : 'Dead'?>
                            </div>
                        </div>
                    <? } ?>
                <?}?>
            </div>
        </div>
    </div>
</div>
