<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width">
        
        <title>Maze RPG Tactics</title>
        <meta name="description" content="Casual dungeon tactic runner based on Phalcon">
        
        <link rel="stylesheet" type="text/css" href="/css/style.css">
        <link rel="icon" href="/img/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon">
        <link href="https://fonts.googleapis.com/css?family=MedievalSharp" rel="stylesheet">
    </head>
    <body>
        <?php echo $this->getContent(); ?>
        <script src="/js/jquery.min.js"></script>
        <script src="/js/script.js"></script>
    </body>
</html>
