<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width">
        
        <title>Maze RPG</title>
        <meta name="description" content="Casual dungeon runner based on Phalcon FW">
        
        <link rel="stylesheet" href="/css/style.css">
    </head>
    <body>
        <?php echo $this->getContent(); ?>
        <script src="/js/jquery.min.js"></script>
    </body>
</html>
